#ifndef __PRINTF_H
#define __PRINTF_H

#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef signed int (*printf_send_func_t)(const unsigned char *, const unsigned int);

extern printf_send_func_t printf_send_func;

/**
 * Sets the function which is used to transmit the 
 * strings generated by printf.
 * */
void printf_setSendFunction(printf_send_func_t function);

void testprintf();

#ifdef __cplusplus
}
#endif

#endif
